apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus-1
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 10s
